version: '2'
services:
  meteor:
    #image: meteor4idevops:latest
    image: meteor4idevops:latest
    container_name: meteor4idevops
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - ROOT_URL=http://localhost
      - MONGO_URL=mongodb://mongo:27017/meteor
      - POLL_DOCKER_STATS=true
      - DOCKER_LOCAL=true
      - DOCKER_POLL=true
      - ZIPKIN_POLL=true
      - NODE_ENV=production
      - ZIPKIN_HOST=localhost
      - ZIPKIN_PORT=9411
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
